export const MODULES = {
  E_PAYROLL: {
    id: 'e-payroll',
    name: 'E-Payroll',
    slug: 'e-payroll',
    description: 'Payroll processing and salary management',
    icon: 'DollarSign',
    color: '#10B981',
    order: 1,
  },
  EMPLOYEE_SELF_SERVICE: {
    id: 'employee-self-service',
    name: 'Employee Self Service',
    slug: 'employee-self-service',
    description: 'Employee portal for self-management',
    icon: 'User',
    color: '#3B82F6',
    order: 2,
  },
  HEALTH_WELLNESS: {
    id: 'health-wellness',
    name: 'Health & Wellness',
    slug: 'health-wellness',
    description: 'Health benefits and wellness programs',
    icon: 'Heart',
    color: '#EF4444',
    order: 3,
  },
  JOB_MANAGEMENT: {
    id: 'job-management',
    name: 'Job Management',
    slug: 'job-management',
    description: 'Job postings and internal positions',
    icon: 'Briefcase',
    color: '#8B5CF6',
    order: 4,
  },
  LEAVE_MANAGEMENT: {
    id: 'leave-management',
    name: 'Leave Management',
    slug: 'leave-management',
    description: 'Leave requests and approvals',
    icon: 'Calendar',
    color: '#F59E0B',
    order: 5,
  },
  ONLINE_JOB_APPLICATION: {
    id: 'online-job-application-portal',
    name: 'Job Application Portal',
    slug: 'online-job-application-portal',
    description: 'External candidate applications',
    icon: 'FileText',
    color: '#06B6D4',
    order: 6,
  },
  PAYROLL_MANAGEMENT: {
    id: 'payroll-management',
    name: 'Payroll Management',
    slug: 'payroll-management',
    description: 'Advanced payroll configuration',
    icon: 'Settings',
    color: '#14B8A6',
    order: 7,
  },
  PERFORMANCE_MANAGEMENT: {
    id: 'performance-management',
    name: 'Performance Management',
    slug: 'performance-management',
    description: 'Employee evaluations and goals',
    icon: 'TrendingUp',
    color: '#F97316',
    order: 8,
  },
  PERSONNEL_INFORMATION: {
    id: 'personnel-information-management',
    name: 'Personnel Information',
    slug: 'personnel-information-management',
    description: 'Employee data management',
    icon: 'Users',
    color: '#6366F1',
    order: 9,
  },
  REPORT_GENERATION: {
    id: 'report-generation',
    name: 'Report Generation',
    slug: 'report-generation',
    description: 'Analytics and reporting',
    icon: 'BarChart',
    color: '#EC4899',
    order: 10,
  },
  SYSTEM_ADMINISTRATION: {
    id: 'system-administration',
    name: 'System Administration',
    slug: 'system-administration',
    description: 'System settings, roles, and permissions',
    icon: 'Shield',
    color: '#64748B',
    order: 11,
  },
  TIMEKEEPING_ATTENDANCE: {
    id: 'timekeeping-attendance',
    name: 'Timekeeping & Attendance',
    slug: 'timekeeping-attendance',
    description: 'Time tracking and attendance',
    icon: 'Clock',
    color: '#84CC16',
    order: 12,
  },
} as const;

export type ModuleId = keyof typeof MODULES;

